name = "tiny-shields"
type = "javascript"
account_id = "e20ebc96b0121ea21bf59ea0a95e7997"
workers_dev = true

[env.production]
route = "https://tinyshields.dev/*"

[site]
bucket = "../tiny-shields-website/dist"
entry-point = "."
