name: Deployment

on:
  push:
    paths:
      - '.github/**'
      - 'tiny-shields-worker/**'
      - 'tiny-shields-website/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Build website
        run: npm run build
        working-directory: tiny-shields-website
        env:
          NODE_ENV: production

      - name: Build worker
        run: npm run build
        working-directory: tiny-shields-worker

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "tiny-shields"
          root: tiny-shields-worker
          entrypoint: "./dist/main.js"
